//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EId { get; set; }
        public string Name { get; set; }
        public int Salary { get; set; }
        public int DepartmentId { get; set; }
        public byte Gender { get; set; }
        public byte JobType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string EmployerName { get; set; }
        public string Street { get; set; }
        public string Landmark { get; set; }
        public string City { get; set; }
        public Nullable<int> CountryId { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Department Department { get; set; }
    }
}
