//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public int AgencyId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public int ZipCode { get; set; }
        public string BillingCode { get; set; }
        public string API_Key { get; set; }
        public string CompanyURL { get; set; }
        public string State { get; set; }
        public int Phone { get; set; }
        public byte[] Logo { get; set; }
        public bool Status { get; set; }
    }
}
